# Generated by Django 5.0.1 on 2024-01-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='audio_link',
            field=models.URLField(blank=True),
        ),
    ]
