# Generated by Django 5.0.1 on 2024-01-08 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_answers_audio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='key_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mainapp.keywords'),
        ),
    ]
